ARG BASE_IMAGE=ubuntu:24.04

### Test env phase
FROM ${BASE_IMAGE} AS test-setup
ARG BASE_IMAGE=ubuntu:24.04

ENV LC_ALL="C.UTF-8"
ENV GTEST_ROOT=/usr/local
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /saunafs
COPY ./tests/install-packages.sh ./tests/
COPY ./tests/llvm.sh ./tests/
RUN --mount=target=/var/lib/apt/lists,type=cache,sharing=locked \
    --mount=target=/var/cache/apt,type=cache,sharing=locked \
    rm -f /etc/apt/apt.conf.d/docker-clean && \
	apt-get update && apt-get install tini && \
    ./tests/install-packages.sh;

### Build Phase
FROM test-setup AS test-build

# Enable additional basic tools
ENV PATH="/usr/lib/ccache:${PATH}"

# TODO(Urmas): Figure out why binary cache submissions take always 11 seconds.
# For now, just disable it since it's faster with ccache and docker cache.
ENV VCPKG_BINARY_SOURCES="clear"

WORKDIR /
COPY vcpkg /vcpkg
WORKDIR /vcpkg

# Manifest mode doesn't work without git, and we don't want to bring in the
# entire source code of SaunaFS just yet, so we need to remove the .git file
# (if it's a proper submodule) and replace it with the submodule .git in
# saunafs directory. Suprisingly works.
RUN rm -r .git;
COPY .git/modules/vcpkg/ .git

COPY vcpkg.json .
RUN ./bootstrap-vcpkg.sh;
RUN --mount=type=cache,target=/vcpkg/downloads/ \
	./vcpkg install --only-downloads;

ENV VCPKG_ROOT="/vcpkg/"
ENV PATH="${VCPKG_ROOT}:${PATH}"

WORKDIR /saunafs
COPY CMakeLists.txt .
COPY cmake ./cmake
COPY config.h.in .
COPY external ./external
COPY utils ./utils
COPY src ./src
COPY doc ./doc
COPY tests ./tests
COPY COPYING .
COPY README.md .
RUN cp /vcpkg/vcpkg.json .;

ENV CMAKE_C_COMPILER_LAUNCHER=ccache
ENV CMAKE_CXX_COMPILER_LAUNCHER=ccache

RUN --mount=type=cache,target=/vcpkg/downloads/ \
    --mount=type=cache,target=/root/.ccache \
	--mount=type=cache,target=/vcpkg/packages/ \
	ccache -s && mkdir -p /saunafs/build && ls /saunafs && \
    cd /saunafs/build && cmake \
	-DCMAKE_TOOLCHAIN_FILE="/vcpkg/scripts/buildsystems/vcpkg.cmake" \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DPROMETHEUS_ENABLED=OFF \
	-DCMAKE_C_COMPILER=clang \
	-DCMAKE_CXX_COMPILER=clang++-19 \
    -DENABLE_TESTS=1 \
    -DENABLE_NFS_GANESHA=1 \
    -DENABLE_CLIENT_LIB=ON \
    .. && ccache -s;

# TODO: Use CMake presets
RUN --mount=type=cache,target=/root/.ccache \
    cd /saunafs/build && make -j$(nproc);
