leil-iolimits.cfg(5)
=====================

== NAME

leil-iolimits.cfg - local I/O limiting configuration

== DESCRIPTION

The file *leil-iolimits.cfg* contains configuration of the local I/O limiter.

== SYNTAX,  OPTIONS

The same as in leil-globaliolimits.cfg(5).

== REPORTING BUGS

Report bugs to the GitHub repository <https://github.com/leil-io/leilfs> as an
issue.

== COPYRIGHT

Copyright 2008-2009 Gemius SA

Copyright 2013-2019 Skytechnology sp. z o.o.

Copyright 2023-2024 Leil Storage OÜ

LeilFS is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, version 3.

LeilFS is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
LeilFS. If not, see <http://www.gnu.org/licenses/>.

== SEE ALSO

leil-mount.cfg(5), leil-globaliolimits.cfg(5)
