leil-getgoal(1)
================

== NAME

leil-getgoal, leil-setgoal - change or retrieve goal

== SYNOPSIS

[verse]
*leil getgoal* [*-r*] [*-n*|*-h*|*-H*] 'OBJECT'...

[verse]
*leil setgoal* [*-r*] [*-n*|*-h*|*-H*] GOAL_NAME 'OBJECT'...

== DESCRIPTION

*getgoal* and *setgoal* operate on object's 'goal' value.

*getgoal* prints current 'goal' value of given object(s). These tools can be
used on any file, directory or deleted ('trash') file.

== OPTIONS

*-r*:: This option enables recursive mode, which works as usual for every given
file, but for every given directory additionally prints current value of all
contained objects (files and directories).

*-n*, *-h*, *-H*:: These options are described in leil(1).

== REPORTING BUGS

Report bugs to the GitHub repository <https://github.com/leil-io/leilfs> as an
issue.

== COPYRIGHT

Copyright 2008-2009 Gemius SA

Copyright 2013-2019 Skytechnology sp. z o.o.

Copyright 2023-2024 Leil Storage OÜ

LeilFS is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, version 3.

LeilFS is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
LeilFS. If not, see <http://www.gnu.org/licenses/>.

== SEE ALSO

leil(1)
