leil-hdd.cfg(5)
================

== NAME

leil-hdd.cfg - list of LeilFS storage directories for leil-chunkserver

== DESCRIPTION

The file *leil-hdd.cfg* contains list of directories (mountpoints) used for
LeilFS storage (one per line). Directory prefixed by */** character causes
given directory to be freed by replicating all data already stored there to
another locations. Lines starting with *#* character are ignored.

The chunks are divided into metadata (.met) and data (.dat) parts. The metadata
parts contain information about the chunks, while data parts are only aligned
data. It is possible to store the metadata parts in a different directory, or
even in a separate drive, by splitting both paths using ' | ':

----
/path/to/metadata | /path/to/data
----

This way, the metadata parts can be stored, for instance, in NVMe and the data
parts in HDD.

=== HOST-MANAGED SMR SPECIFICS

With the proprietary chunkserver plugin for Host-Managed SMR drives, use the
`zonefs:` prefix with the following syntax:

----
[*]zonefs:/path/to/metadata | /path/to/data
----

For example:

----
zonefs:/mnt/nvme1 | /mnt/host-managed-smr1
----

Note that the `/path/to/metadata` should always be on a non-SMR drive. The
optional `*` has the same meaning as described above and marks the drive for
removal.

== REPORTING BUGS

Report bugs to the GitHub repository <https://github.com/leil-io/leilfs> as an
issue.

== COPYRIGHT

Copyright 2008-2009 Gemius SA

Copyright 2013-2019 Skytechnology sp. z o.o.

Copyright 2023-2024 Leil Storage OÜ

LeilFS is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, version 3.

LeilFS is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
LeilFS. If not, see <http://www.gnu.org/licenses/>.

== SEE ALSO

leil-chunkserver(8), leil-chunkserver.cfg(5)
