leil-metalogger(8)
===================

== NAME

leil-metalogger - start, restart or stop Leil File System metalogger process

== SYNOPSIS

[verse]
*leil-metalogger* [*-c* 'CFGFILE'] [*-u*] [*-d*] [*-t* 'LOCKTIMEOUT'] ['ACTION']

[verse]
*leil-metalogger -s* [*-c* 'CFGFILE']

[verse]
*leil-metalogger -v*

[verse]
*leil-metalogger -h*

== DESCRIPTION

*leil-metalogger* is the metadata replication server of LeilFS. Depending on parameters it
can start, restart or stop LeilFS metalogger process. Without any options it starts LeilFS
metalogger, killing previously run process if lock file exists.

SIGHUP (or 'reload' 'ACTION') forces *leil-metalogger* to reload all configuration files.

*-v*::
print version information and exit

*-h*::
print usage information and exit

*-c* 'CFGFILE'::
specify alternative path of configuration file (default is *leil-metalogger.cfg* in system
configuration directory)

*-u*::
log undefined configuration values (when default is assumed)

*-d*::
run in foreground, don't daemonize

*-t* 'LOCKTIMEOUT'::
how long to wait for lockfile (default is 60 seconds)

'ACTION'
is the one of *start*, *stop*, *restart*, *reload*, *test*, *isalive* or *kill*. Default action is
*restart*.

== FILES

*leil-metalogger.cfg*::
configuration file for LeilFS metalogger process; refer to *leil-metalogger.cfg*(5) manual for
details

*sfsmetalogger.lock*::
PID file of running LeilFS metalogger process

*.sfsmetalogger.lock*::
lock file of running LeilFS metalogger process
(created in data directory)

*changelog_ml.***.sfs*::
LeilFS filesystem metadata change logs (backup of master change log files)

*metadata.ml.sfs.back*::
Latest copy of complete metadata.sfs.back file from LeilFS master.

*sessions.ml.sfs*::
Latest copy of sessions.sfs file from LeilFS master.

== REPORTING BUGS

Report bugs to the GitHub repository <https://github.com/leil-io/leilfs> as an
issue.

== COPYRIGHT

Copyright 2008-2009 Gemius SA

Copyright 2013-2019 Skytechnology sp. z o.o.

Copyright 2023-2024 Leil Storage OÜ

LeilFS is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, version 3.

LeilFS is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
LeilFS. If not, see <http://www.gnu.org/licenses/>.

== SEE ALSO

leil-master(8), leil-metalogger.cfg(5), leilfs(7)
