saunafs-fileinfo(1)
====================

== NAME

saunafs-fileinfo - locate chunks

== SYNOPSIS

[verse]
*saunafs fileinfo* 'FILE'...

== DESCRIPTION

*fileinfo* prints location ('chunkserver' host and port) of each chunk copy
belonging to specified file(s). It can be used on any file, included deleted
('trash').

== OPTIONS

*-l*::
This option disables timeout set for this operation. (default timeout is 10 seconds)

This behavior will be default and the option removed starting from 5.0.0. If you wish
to have timeouts use the `timeout` command.

== REPORTING BUGS

Report bugs to the Github repository <https://github.com/leil/saunafs> as an
issue.

== COPYRIGHT

Copyright 2008-2009 Gemius SA

Copyright 2013-2019 Skytechnology sp. z o.o.

Copyright 2023-2024 Leil Storage OÜ

SaunaFS is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, version 3.

SaunaFS is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
SaunaFS. If not, see <http://www.gnu.org/licenses/>.

== SEE ALSO

saunafs(1)
