sfsrestoremaster(8)
===================

== NAME

sfsrestoremaster - scripts automating starting master server on a metalogger machine.

== SYNOPSIS

[verse]
*sfsrestoremaster* '<net-interface>' '[<etc-sau-dir>]'

*<net-interface>*::
Network interface to reconfigure.

*<etc-sau-dir>*::
SaunaFS configuration directory to use (default: `/etc/saunafs`).

== DESCRIPTION

This scripts performs the following steps:

* verify basic sanity of configuration files,
* update metadata image with data from metalogger changelogs,
* set master's IP address on given network interface,
* start the master server.

== NOTES

`sfsrestoremaster` makes use of `sfsmetarestore`.

== REPORTING BUGS

Report bugs to the GitHub repository <https://github.com/leil-io/saunafs> as an
issue.

== COPYRIGHT

Copyright 2008-2009 Gemius SA

Copyright 2013-2019 Skytechnology sp. z o.o.

Copyright 2023-2024 Leil Storage OÜ

SaunaFS is free software: you can redistribute it and/or modify it under the
terms of the GNU General Public License as published by the Free Software
Foundation, version 3.

SaunaFS is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
SaunaFS. If not, see <http://www.gnu.org/licenses/>.

== SEE ALSO

sfsmetarestore(8)
