# Insecure workflow with limited permissions that should provide analysis results through an artifact
name: Static analysis

on: pull_request

jobs:
  clang-tidy:
    runs-on: ubuntu-24.04
    steps:

    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        submodules: true
        fetch-depth: 0

    - name: Install nfs-ganesha v4.3 from Ubuntu repository
      run: |
          sudo apt update
          sudo apt install -y nfs-common nfs-ganesha nfs-ganesha-vfs

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: "3.x"

    - name: Install SaunaFS dependencies, setup environment and build
      run: |
        sudo mkdir /mnt/hd{b,c,d}
        cd $GITHUB_WORKSPACE/tests
        sudo ./setup_machine.sh setup /mnt/hdb /mnt/hdc /mnt/hdd

    - name: Fetch base branch
      run: |
        git remote add upstream "https://github.com/${{ github.event.pull_request.base.repo.full_name }}"
        git fetch --no-tags --no-recurse-submodules upstream "${{ github.event.pull_request.base.ref }}"

    - name: Install clang-tidy
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy libc++-18-dev
        pip3 install PyYAML

    - name: Install LLVM and Clang
      run: |
          sudo $GITHUB_WORKSPACE/tests/llvm.sh

    - name: Cache vcpkg downloads
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/vcpkg
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Setup vcpkg and install dependencies
      run: |
        $GITHUB_WORKSPACE/utils/vcpkg_setup.sh
        vcpkg install --triplet x64-linux

    - name: Prepare compile_commands.json
      run: |
        mkdir -p build
        cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE="${HOME}/vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DENABLE_CLIENT_LIB=ON \
            -DENABLE_DOCS=ON \
            -DENABLE_NFS_GANESHA=ON \
            -DENABLE_POLONAISE=OFF \
            -DENABLE_URAFT=ON \
            -DGSH_CAN_HOST_LOCAL_FS=ON \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DCMAKE_INSTALL_PREFIX="${GITHUB_WORKSPACE}/install/saunafs/" \
            -DENABLE_TESTS=ON \
            -DCODE_COVERAGE=OFF \
            -DSAUNAFS_TEST_POINTER_OBFUSCATION=ON \
            -DENABLE_WERROR=ON \

    - name: Create results directory
      run: |
        mkdir clang-tidy-result

    - name: Analyze
      run: |
        git diff -U0 "$(git merge-base HEAD "upstream/${{ github.event.pull_request.base.ref }}")" | clang-tidy-diff -p1 -path build -export-fixes clang-tidy-result/fixes.yml

    - name: Save PR metadata
      run: |
        echo "${{ github.event.number }}" > clang-tidy-result/pr-id.txt
        echo "${{ github.event.pull_request.head.repo.full_name }}" > clang-tidy-result/pr-head-repo.txt
        echo "${{ github.event.pull_request.head.sha }}" > clang-tidy-result/pr-head-sha.txt

    - uses: actions/upload-artifact@v4
      with:
        name: clang-tidy-result
        path: clang-tidy-result/
